import {
  LayoutDashboard,
  ListChecks,
  Presentation,
  Users,
  UserCog,
  UserCircle,
  Building2,
  LogOut,
  Menu,
  ShieldCheck,
  MessagesSquare,
  FileBarChart,
  ClipboardCheck,
  UsersRound,
  UserRoundCheck,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const icons: Record<string, LucideIcon> = {
  LayoutDashboard,
  ListChecks,
  Presentation,
  Users,
  UserCog,
  UserCircle,
  Building2,
  LogOut,
  Menu,
  ShieldCheck,
  MessagesSquare,
  FileBarChart,
  ClipboardCheck,
  UsersRound,
  UserRoundCheck,
};
