ALTER TABLE "CoachingRecord"
ADD COLUMN IF NOT EXISTS "sessionNumber" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS "totalSessions" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'NOT_STARTED';

UPDATE "CoachingRecord"
SET "status" = CASE
  WHEN COALESCE("resultOutcome", '') <> '' THEN 'COMPLETED'
  WHEN "coachingDate" <= NOW() THEN 'IN_PROGRESS'
  ELSE 'NOT_STARTED'
END;
