export type TalentSeed = {
  name: string;
  email: string;
  nik: string;
  phone?: string;
  birthDate?: string;
  department: string;
  division: string;
  directorate: string;
  position: string;
  jobDescription: string;
  joinDate: string;
  supervisorName: string;
  workLocation: string;
  jobLevel: string;
  performance: number[];
  potential: number;
  readiness: number;
  technical: string[];
  behavioral: string[];
  certifications: string[];
  developmentPrograms: string[];
  projects: string[];
  projectImpact?: string;
  careerHistory: string[];
  aspiration: string;
  strength: string[];
  weakness: string[];
  lastPromotionDate?: string;
  currentPositionDuration?: string;
  talentClass?: string;
  promotionStatus?: string;
  nextPromotionPic?: string;
  supervisorNotes?: string;
  hse: { mcu: string; simper: string; incidentFreeMonths: number; summary?: string };
  assessment: { iq: number; eq: number; leadership: number };
};

// Source: sample_input_berau_5orang_terisi.xlsx, sheets Employee and DP.
// Employee sheet contributes the full employee sample, DP sheet contributes all DP/Fast Track rows.
export const TALENT_EMPLOYEES: TalentSeed[] = [
  {
    name: "Arintoko Saputro",
    email: "arintoko@beraucoal.co.id",
    nik: "11000433",
    phone: "6281352987207",
    birthDate: "1981-02-21",
    directorate: "OPERATION & HSE DIRECTORATE",
    division: "MINE OPERATION & SUPPORT DIVISION",
    department: "BINUNGAN MINE OPERATION AREA 2 DEPT",
    position: "Binungan Mine Operation Area 2 Manager",
    jobDescription: "Kegiatan operasional penambangan dan pemrosesan batubara berjalan dengan baik sesuai dengan rencana kerja harian, mingguan dan bulanan.",
    joinDate: "2008-10-15",
    supervisorName: "Maurys Irwan",
    workLocation: "Binungan Area02",
    jobLevel: "5DEP",
    performance: [92, 96, 96],
    potential: 94,
    readiness: 88,
    technical: ["Competent in different roles", "Mine operation management"],
    behavioral: ["Koordinasi bagus", "Prioritization", "Customer response"],
    certifications: ["Minimal 3 across function certification"],
    developmentPrograms: ["ECDP"],
    projects: ["Project Leader", "Tangible", "Across Dept./Div. (Within BU)"],
    projectImpact: "Tangible",
    careerHistory: ["Experience in different roles"],
    aspiration: "Senior Manager",
    strength: ["Koordinasi bagus", "Mampu melakukan pengaturan dan prioritas kerja dengan baik"],
    weakness: ["Keep a fight", "Respons ke customer perlu ditingkatkan"],
    lastPromotionDate: "2020-01-14",
    currentPositionDuration: "0 Years 11 Months",
    talentClass: "STAR",
    promotionStatus: "Verified by HROD",
    nextPromotionPic: "Approved Dir./Bus. Head / Arief Wiedhartono",
    supervisorNotes: "Based on his experience and outstanding achievements on the BMO2 site, he unquestionably deserves a promotion.",
    hse: { mcu: "FIT Untuk Bekerja", simper: "aktif", incidentFreeMonths: 36, summary: "FIT Untuk Bekerja" },
    assessment: { iq: 120, eq: 100, leadership: 90 },
  },
  {
    name: "Muhammad Sulaiman",
    email: "sulaiman.muhammad@beraucoal.co.id",
    nik: "11000078",
    phone: "628125401050",
    birthDate: "1972-01-10",
    directorate: "OPERATION & HSE DIRECTORATE",
    division: "OPERATION & SUPPORT RELATION DIV",
    department: "COMMUNITY RELATION DEPARTMENT",
    position: "Community Relation Manager",
    jobDescription: "Penanggung jawab aktivitas dan program departemen untuk membangun hubungan harmonis antara PT Berau Coal dengan masyarakat sekitar dan menyelesaikan isu eksternal akibat kegiatan operasional perusahaan.",
    joinDate: "1995-02-20",
    supervisorName: "Cahyo Andrianto",
    workLocation: "Tanjung Redeb",
    jobLevel: "5DEP",
    performance: [92, 92, 92],
    potential: 94,
    readiness: 84,
    technical: ["Competent in similar roles", "Community approach", "Social issue handling"],
    behavioral: ["Visionary leadership", "Professional decision making", "Department coordination"],
    certifications: ["Minimal 3 across function certification"],
    developmentPrograms: [],
    projects: ["Project Leader", "Tangible", "Across Dept./Div. (Within BU)"],
    projectImpact: "Tangible",
    careerHistory: ["Experience in similar roles"],
    aspiration: "Senior Manager",
    strength: ["Koordinasi antar department", "Community approach", "Kinerja baik"],
    weakness: ["Keberanian mengambil risiko perlu ditingkatkan", "Managerial skill perlu terus diperkuat"],
    lastPromotionDate: "2021-01-01",
    currentPositionDuration: "0 Years 3 Months",
    talentClass: "STAR",
    promotionStatus: "Verified by HROD",
    nextPromotionPic: "Approved Dir./Bus. Head / Arief Wiedhartono",
    supervisorNotes: "Pak MSL, Perform good perfomance result in handling social issue among mine site. in 2023 mostly social permit can get from stakeholder (AMDAL GMO).\nHe also get tour of duty as CBD manager in 2023 and perform good progress",
    hse: { mcu: "FIT Untuk Bekerja", simper: "aktif", incidentFreeMonths: 36, summary: "FIT Untuk Bekerja" },
    assessment: { iq: 120, eq: 100, leadership: 90 },
  },
  {
    name: "Rayhan Fajusha",
    email: "rayhan.fajusha@beraucoal.co.id",
    nik: "11000725",
    phone: "6281399390020",
    birthDate: "1989-07-29",
    directorate: "OPERATION & HSE DIRECTORATE",
    division: "MINE PLANNING & TECH. SERVICES DIVISION",
    department: "MINE DEV & PRODUCTION CONTROL DEPT",
    position: "Mine Dev & Production Control Manager",
    jobDescription: "Mengelola pengembangan tambang dan pengendalian produksi untuk memastikan rencana, kemajuan, kualitas, biaya, dan target operasional pertambangan tercapai secara aman dan efektif.",
    joinDate: "2011-11-23",
    supervisorName: "Sutami Sitorus",
    workLocation: "Tanjung Redeb",
    jobLevel: "5DEP",
    performance: [92, 92, 92],
    potential: 94,
    readiness: 88,
    technical: ["Competent in different roles", "Production control", "Business process automation"],
    behavioral: ["Integrity", "Collaboration", "Effective communication"],
    certifications: ["Minimal 3 across function certification"],
    developmentPrograms: ["ECDP"],
    projects: ["Project Leader", "Tangible", "Within Dept./Div.", "DMS first trial", "Coal supply chain acceleration"],
    projectImpact: "Tangible",
    careerHistory: ["Experience in different roles"],
    aspiration: "Senior Manager",
    strength: ["Ide selalu dibagikan ke sekitar", "Integritas tinggi", "Respon cepat dalam pekerjaan"],
    weakness: ["Peningkatan kompetensi melalui pelatihan dan sertifikasi", "Empati terhadap orang sekitar perlu ditingkatkan"],
    lastPromotionDate: "2019-12-01",
    currentPositionDuration: "1 Years 8 Months",
    talentClass: "STAR",
    promotionStatus: "Verified by HROD",
    nextPromotionPic: "Approved Dir./Bus. Head / Arief Wiedhartono",
    supervisorNotes: "1. Performa kerja yg baik, control issue2 operasional\n2. Melakukan beberapa Improvement seperti:\n- 2020: DMS first trial\n- 2021: efficiency program at Plant Dept MTL\n- 2022: business process automation map MTL\n- 2023: coal supply chain, acceleration of FS approval\n3. Terakhir promosi tahun 2019",
    hse: { mcu: "FIT Untuk Bekerja", simper: "aktif", incidentFreeMonths: 36, summary: "FIT Untuk Bekerja" },
    assessment: { iq: 120, eq: 100, leadership: 90 },
  },
  {
    name: "Reza Hermawan",
    email: "reza.hermawan@beraucoal.co.id",
    nik: "11000390",
    phone: "628115410508",
    birthDate: "1984-04-01",
    directorate: "OPERATION & HSE DIRECTORATE",
    division: "OPERATION & SUPPORT RELATION DIV",
    department: "COMMUNITY BASE DEVELOPMENT DEPARTMENT",
    position: "Community Base Development Manager (Act)",
    jobDescription: "Penanggung jawab pengelolaan program pengembangan dan pemberdayaan masyarakat lingkar tambang dan tanggung jawab sosial perusahaan.",
    joinDate: "2008-02-15",
    supervisorName: "Cahyo Andrianto",
    workLocation: "Tanjung Redeb",
    jobLevel: "4SEC",
    performance: [92, 92, 92],
    potential: 94,
    readiness: 84,
    technical: ["Competent in different roles", "Community development", "Cross-department collaboration"],
    behavioral: ["Dedication", "Commitment", "Collaboration"],
    certifications: ["Minimal 2 across function certification"],
    developmentPrograms: [],
    projects: ["Project Leader", "Tangible", "Within Dept./Div."],
    projectImpact: "Tangible",
    careerHistory: ["Experience in different roles"],
    aspiration: "Senior Manager",
    strength: ["Dedikasi dan komitmen tinggi", "Kolaborasi baik dengan rekan kerja"],
    weakness: ["Pengambilan keputusan sesuai kewenangan perlu ditingkatkan", "Inovasi dan leadership perlu terus diperkuat"],
    lastPromotionDate: "2022-01-01",
    currentPositionDuration: "0 Years 11 Months",
    talentClass: "STAR",
    promotionStatus: "Verified by HROD",
    nextPromotionPic: "Approved Dir./Bus. Head / Arief Wiedhartono",
    supervisorNotes: "Holding new role.as Dept coordinator",
    hse: { mcu: "FIT Untuk Bekerja", simper: "aktif", incidentFreeMonths: 36, summary: "FIT Untuk Bekerja" },
    assessment: { iq: 120, eq: 100, leadership: 90 },
  },
  {
    name: "Salahuddin Al Rasyid",
    email: "salahuddin.alrasyid@beraucoal.co.id",
    nik: "11000468",
    phone: "6281382049166",
    birthDate: "1980-09-08",
    directorate: "OPERATION & HSE DIRECTORATE",
    division: "OCCUPATIONAL HEALTH & SAFETY DIVISION",
    department: "SAFETY OPERATIONS DEPARTMENT",
    position: "Safety Operation Manager (Act)",
    jobDescription: "Memimpin terwujudnya pelaksanaan Berau Coal Green Mining System untuk keselamatan kerja operasional pertambangan berdasarkan regulasi, peraturan, dan standar perusahaan.",
    joinDate: "2009-04-02",
    supervisorName: "Jimmi Idris",
    workLocation: "Binungan Area02",
    jobLevel: "4SEC",
    performance: [86, 92, 92],
    potential: 94,
    readiness: 84,
    technical: ["Competent in different roles", "Safety operations", "Green field mine management"],
    behavioral: ["Leadership", "Decision making", "People management"],
    certifications: ["Minimal 2 across function certification"],
    developmentPrograms: [],
    projects: ["Project Leader", "Tangible", "Within Dept./Div."],
    projectImpact: "Tangible",
    careerHistory: ["Experience in different roles"],
    aspiration: "Senior Manager",
    strength: [],
    weakness: [],
    lastPromotionDate: "2019-01-01",
    currentPositionDuration: "0 Years 4 Months",
    talentClass: "STAR",
    promotionStatus: "Verified by HRBP",
    nextPromotionPic: "Verified by HROD / Widya Kusuma ST",
    supervisorNotes: "He has been chosen as the new mine manager, who will manage our new green field at B10. To perform his tasks with leadership and decision-making skills, it is crucial to undergo training. Additionally, it is recommended to take HR training for managing people and handling challenging individuals.",
    hse: { mcu: "FIT Untuk Bekerja", simper: "aktif", incidentFreeMonths: 36, summary: "FIT Untuk Bekerja" },
    assessment: { iq: 120, eq: 100, leadership: 90 },
  },
  {
    name: "Muhammad Adi Prasojo",
    email: "adi.prasojo@beraucoal.co.id",
    nik: "11001591",
    phone: "628111933030",
    birthDate: "1993-03-30",
    directorate: "OPERATION & HSE DIRECTORATE",
    division: "MINE PLANNING & TECH. SERVICES DIVISION",
    department: "GEOTECHNIC & HYDROLOGY DEPT",
    position: "Geotechnical Sr Engineer",
    jobDescription: "Melaksanakan kajian, pemantauan, dan pengendalian geoteknik untuk memastikan kestabilan lereng dan keselamatan kegiatan operasional pertambangan.",
    joinDate: "2017-11-01",
    supervisorName: "Lukman Hakim",
    workLocation: "Lati",
    jobLevel: "4F",
    performance: [92, 92, 92],
    potential: 84,
    readiness: 88,
    technical: ["Competent in one role", "Geotechnical engineering", "Project leadership"],
    behavioral: ["Assertiveness", "Follow-up discipline", "Team communication"],
    certifications: ["Minimal 2 across function certification"],
    developmentPrograms: ["GDP"],
    projects: ["Project Leader", "Tangible", "Across Dept./Div. (Within BU)"],
    projectImpact: "Tangible",
    careerHistory: ["2025 - Present: Geotechnical Sr Engineer", "2023 - 2023: Senior Geotechnical Engineer", "2016 - BP: Subsurface Exploration Intern", "2016 - SKK Migas: Technical Staff"],
    aspiration: "",
    strength: ["Assertive dalam menyatakan pendapat", "Cepat follow up", "Komunikasi dan teamwork baik"],
    weakness: ["Perlu lebih berani mengambil risiko", "Konsistensi performa perlu dipertahankan"],
    lastPromotionDate: "2025-01-01",
    currentPositionDuration: "1 Years 3 Months",
    talentClass: "Growing Talent",
    promotionStatus: "Submitted",
    nextPromotionPic: "Approved Div. Head / Arya Dhamar Nugraha",
    supervisorNotes: "Performa exceed expectations, mampu memimpin, rating memenuhi persyaratan promosi.",
    hse: { mcu: "FIT Untuk Bekerja", simper: "aktif", incidentFreeMonths: 36, summary: "FIT Untuk Bekerja" },
    assessment: { iq: 120, eq: 90, leadership: 88 },
  },
  {
    name: "Saeful Aziz",
    email: "saeful.aziz@beraucoal.co.id",
    nik: "11001451",
    phone: "6281319494923",
    birthDate: "1994-09-14",
    directorate: "OPERATION & HSE DIRECTORATE",
    division: "MINE OPERATION & SUPPORT DIVISION",
    department: "BINUNGAN MINE OPERATION AREA 2 DEPT",
    position: "B7 Mining Section Superintendent",
    jobDescription: "Terkoordinirnya operasional penambangan di area yang menjadi tanggung jawabnya sesuai dengan perencanaan yang telah dibuat.",
    joinDate: "2017-03-31",
    supervisorName: "Arintoko Saputro",
    workLocation: "Binungan Area02",
    jobLevel: "4D",
    performance: [92, 92, 96],
    potential: 82,
    readiness: 88,
    technical: ["Competent in different roles", "Mining operations", "Downstream project"],
    behavioral: ["Discipline", "Persistence", "Commitment"],
    certifications: ["Minimal 2 across function certification"],
    developmentPrograms: ["GDP"],
    projects: ["2", "Tangible", "Within Dept./Div."],
    projectImpact: "Tangible",
    careerHistory: ["2026 - Present: Downstream Project Senior", "2024 - 2025: B7 Mining Section Superintendent"],
    aspiration: "",
    strength: ["Disiplin dalam menjalankan tugas", "Gigih dan support ke anggota", "Kritis dan komitmen"],
    weakness: ["Ketegasan ke bawahan perlu ditingkatkan", "Bonding dengan bawahan perlu ditingkatkan"],
    lastPromotionDate: "2024-01-01",
    currentPositionDuration: "0 Years 4 Months",
    talentClass: "Emerging Leaders",
    promotionStatus: "Verified by HRBP",
    nextPromotionPic: "Verified by HROD / Widya Kusuma ST",
    supervisorNotes: "Memperkuat dan melengkapi basic mining operasional",
    hse: { mcu: "FIT Untuk Bekerja", simper: "aktif", incidentFreeMonths: 36, summary: "FIT Untuk Bekerja" },
    assessment: { iq: 120, eq: 90, leadership: 88 },
  },
  {
    name: "Ridho Ilham Mury Nanda",
    email: "ridho.ilham@beraucoalenergy.co.id",
    nik: "11001592",
    phone: "6281224569946",
    birthDate: "1996-11-03",
    directorate: "OPERATION & HSE DIRECTORATE",
    division: "OCCUPATIONAL HEALTH & SAFETY DIVISION",
    department: "SAFETY OPERATIONS DEPARTMENT",
    position: "Gurimbang Safety Superintendent",
    jobDescription: "Koordinator kegiatan keselamatan operasional untuk memastikan lokasi kerja aman, risiko terkendali, dan kesadaran karyawan dalam bertindak benar dan aman meningkat.",
    joinDate: "2017-11-01",
    supervisorName: "Salahuddin Al Rasyid",
    workLocation: "Binungan Area02",
    jobLevel: "4F",
    performance: [92, 92, 92],
    potential: 82,
    readiness: 88,
    technical: ["Competent in different roles", "Safety operations", "Risk control"],
    behavioral: ["Communication", "Teamwork", "Consistency"],
    certifications: ["Minimal 2 across function certification"],
    developmentPrograms: ["GDP"],
    projects: ["Project Leader", "Tangible", "Within Dept./Div."],
    projectImpact: "Tangible",
    careerHistory: ["2025 - Present: Gurimbang Safety Superintendent", "2023 - 2024: BMO 2 Blok 7 Safety Superintendent"],
    aspiration: "",
    strength: ["Berkomunikasi dengan baik", "Kerja sama baik", "Konsisten pada nilai yang baik"],
    weakness: ["Pengawasan pencegahan accident perlu fokus", "Constructive feedback", "Alokasi sumber daya perlu diperkuat"],
    lastPromotionDate: "2025-01-01",
    currentPositionDuration: "2 Years 1 Months",
    talentClass: "Emerging Leaders",
    promotionStatus: "Submitted",
    nextPromotionPic: "Approved Div. Head / Jimmi Idris",
    supervisorNotes: "Support project improvement di SOD\n1. Mempunyai semangat kerja yang tinggi\n2. Memiliki komunikasi yang sangat baik\n3. Memiliki kemampuan leadership yang sangat baik\n4. Mempunyai kedisiplinan dan tanggung jawab yang tinggi dalam menjalankan tugasnya",
    hse: { mcu: "FIT Untuk Bekerja", simper: "aktif", incidentFreeMonths: 36, summary: "FIT Untuk Bekerja" },
    assessment: { iq: 120, eq: 90, leadership: 88 },
  },
  {
    name: "Paian Mhm Siregar",
    email: "paian.siregar@beraucoal.co.id",
    nik: "11000928",
    phone: "6281271392169",
    birthDate: "1986-03-07",
    directorate: "OPERATION & HSE DIRECTORATE",
    division: "OCCUPATIONAL HEALTH & SAFETY DIVISION",
    department: "SAFETY OPERATIONS DEPARTMENT",
    position: "Parapatan Safety Superintendent",
    jobDescription: "Koordinator kegiatan untuk membuat lokasi kerja sehat dan aman serta menumbuhkan kesadaran karyawan untuk bertindak benar dan aman.",
    joinDate: "2012-11-16",
    supervisorName: "Salahuddin Al Rasyid",
    workLocation: "Sambarata",
    jobLevel: "4E",
    performance: [92, 86, 92],
    potential: 82,
    readiness: 88,
    technical: ["Competent in different roles", "Safety operations", "Production supervision"],
    behavioral: ["Responsibility", "Discipline", "Project execution"],
    certifications: ["Minimal 2 across function certification"],
    developmentPrograms: ["MDP"],
    projects: ["Project Leader", "Intangible", "Across Dept./Div. (Within BU)"],
    projectImpact: "Intangible",
    careerHistory: ["2024 - Present: Parapatan Safety Superintendent", "2023 - 2024: Safety Superintendent SMO", "2012 - PT Bara Anugerah Sejahtera: Production Supervisor", "2011 - PT Max Prima Coal: Production Supervisor"],
    aspiration: "",
    strength: ["Jujur dan bertanggung jawab", "Konsisten pada nilai yang baik"],
    weakness: ["Data-driven decision approach perlu diperkuat", "Open feedback culture perlu ditingkatkan", "Delegasi perlu diperkuat"],
    lastPromotionDate: "2023-01-01",
    currentPositionDuration: "2 Years 3 Months",
    talentClass: "Emerging Leaders",
    promotionStatus: "Submitted",
    nextPromotionPic: "Approved Div. Head / Jimmi Idris",
    supervisorNotes: "Sebagai leader berbagai project improvement di SOD\n1. Bertanggung jawab terhadap tugas yang diberikan, tidak pernah menunda pekerjaan.\n2. Tidak pernah telat datang kerja.\n3. Mengerjakan seluruh project dengan baik\n4. Berperan serta sehingga zero injury accident.",
    hse: { mcu: "FIT Untuk Bekerja", simper: "aktif", incidentFreeMonths: 36, summary: "FIT Untuk Bekerja" },
    assessment: { iq: 120, eq: 90, leadership: 88 },
  },
  {
    name: "Dhehave Riaviandhi",
    email: "dhehave@beraucoal.co.id",
    nik: "11001582",
    phone: "6281282296561",
    birthDate: "1993-10-25",
    directorate: "OPERATION & HSE DIRECTORATE",
    division: "OCCUPATIONAL HEALTH & SAFETY DIVISION",
    department: "SAFETY OPERATIONS DEPARTMENT",
    position: "Safety Superintendent SMO",
    jobDescription: "Koordinator kegiatan keselamatan operasional untuk memastikan lokasi kerja aman, risiko terkendali, dan penerapan standar keselamatan berjalan konsisten.",
    joinDate: "2017-07-10",
    supervisorName: "Salahuddin Al Rasyid",
    workLocation: "Binungan Area02",
    jobLevel: "4D",
    performance: [92, 92, 92],
    potential: 82,
    readiness: 88,
    technical: ["Competent in different roles", "Safety operations", "Geology exposure"],
    behavioral: ["Attention to detail", "Hardworking", "Teamwork"],
    certifications: ["Minimal 2 across function certification"],
    developmentPrograms: ["GDP"],
    projects: ["Project Leader", "Intangible", "Across Dept./Div. (Within BU)"],
    projectImpact: "Intangible",
    careerHistory: ["2024 - Present: Safety Superintendent SMO", "2024 - 2024: Blok 10 Safety Superintendent", "2016 - PT. Kamirzu: Wellsite Geologist", "2015 - Energi Mega Persada: Petroleum Geologist"],
    aspiration: "",
    strength: ["Attention to detail", "Hardworking", "Bekerja keras dan fokus pada tujuan perusahaan"],
    weakness: ["Persuasive skill dan leadership perlu ditingkatkan", "Problem solving perlu diperkuat"],
    lastPromotionDate: "2024-01-01",
    currentPositionDuration: "0 Years 4 Months",
    talentClass: "Emerging Leaders",
    promotionStatus: "Verified by HROD",
    nextPromotionPic: "Approved Dir./Bus. Head / Arief Wiedhartono",
    supervisorNotes: "excellent work attitude, Good teamwork, especially between departments, strong will and curiosity, always developing",
    hse: { mcu: "FIT Untuk Bekerja", simper: "aktif", incidentFreeMonths: 36, summary: "FIT Untuk Bekerja" },
    assessment: { iq: 120, eq: 90, leadership: 88 },
  },
];
