export type TalentSeed = {
  name: string;
  email: string;
  nik: string;
  department: string;
  position: string;
  joinDate: string;
  supervisorName: string;
  workLocation: string;
  jobLevel: string;
  performance: number[];
  potential: number;
  readiness: number;
  technical: string[];
  behavioral: string[];
  certifications: string[];
  projects: string[];
  careerHistory: string[];
  aspiration: string;
  hse: { mcu: string; simper: string; incidentFreeMonths: number };
  assessment: { iq: number; eq: number; leadership: number };
};

// Established employees only. These records intentionally do not own
// probation tasks/presentations and represent a mining company's main talent pool.
export const TALENT_EMPLOYEES: TalentSeed[] = [
  { name:"Raka Pratama", email:"raka.pratama@berau.co.id", nik:"BC10021", department:"Mining Operations", position:"Mine Production Superintendent", joinDate:"2013-04-08", supervisorName:"GM Mining Operations", workLocation:"Lati Mine", jobLevel:"M3", performance:[91,89,87], potential:90, readiness:88, technical:["Mine planning","Fleet optimization","Production control","Cost management"], behavioral:["Strategic leadership","Decision making","Stakeholder management"], certifications:["POM","POP","K3 Pertambangan"], projects:["Lati productivity uplift 12%","Fleet dispatch optimization"], careerHistory:["Production Engineer","Mine Supervisor","Mine Production Superintendent"], aspiration:"Mining Operations Manager", hse:{mcu:"Fit",simper:"Aktif",incidentFreeMonths:54}, assessment:{iq:124,eq:88,leadership:91} },
  { name:"Siti Rahmawati", email:"siti.rahmawati@berau.co.id", nik:"BC10034", department:"Human Resources", position:"HR Business Partner", joinDate:"2016-08-15", supervisorName:"HR Manager", workLocation:"Head Office", jobLevel:"M1", performance:[90,88,86], potential:92, readiness:84, technical:["Workforce planning","Talent management","Industrial relations","People analytics"], behavioral:["Coaching","Influencing","Business acumen"], certifications:["Certified HR Professional","Talent Management"], projects:["Critical role succession map","Mine workforce capability review"], careerHistory:["Recruitment Officer","People Development Specialist","HR Business Partner"], aspiration:"HR Manager", hse:{mcu:"Fit",simper:"Tidak diperlukan",incidentFreeMonths:96}, assessment:{iq:121,eq:93,leadership:89} },
  { name:"Budi Santoso", email:"budi.santoso@berau.co.id", nik:"BC10047", department:"Plant Maintenance", position:"Maintenance Supervisor", joinDate:"2012-02-20", supervisorName:"Plant Manager", workLocation:"Binungan Mine", jobLevel:"S3", performance:[86,90,84], potential:83, readiness:82, technical:["Heavy equipment maintenance","Reliability engineering","Shutdown planning","Root cause analysis"], behavioral:["Safety leadership","Team development","Problem solving"], certifications:["POP","CAT Engine","Reliability Maintenance"], projects:["Hauler availability improvement","Predictive maintenance rollout"], careerHistory:["Heavy Equipment Mechanic","Planner","Maintenance Supervisor"], aspiration:"Maintenance Superintendent", hse:{mcu:"Fit",simper:"Aktif",incidentFreeMonths:67}, assessment:{iq:116,eq:82,leadership:86} },
  { name:"Nadia Kusuma", email:"nadia.kusuma@berau.co.id", nik:"BC10059", department:"Finance", position:"Senior Management Accountant", joinDate:"2017-01-09", supervisorName:"Finance Manager", workLocation:"Head Office", jobLevel:"S3", performance:[94,91,90], potential:88, readiness:86, technical:["Budgeting","Mine cost analysis","Financial modeling","SAP FICO"], behavioral:["Analytical thinking","Collaboration","Business partnering"], certifications:["CMA","SAP FICO"], projects:["Pit cost transparency dashboard","Annual budget redesign"], careerHistory:["Cost Accountant","Management Accountant","Senior Management Accountant"], aspiration:"Finance Business Partner Manager", hse:{mcu:"Fit",simper:"Tidak diperlukan",incidentFreeMonths:84}, assessment:{iq:128,eq:86,leadership:85} },
  { name:"Arif Hidayat", email:"arif.hidayat@berau.co.id", nik:"BC10063", department:"HSE", position:"Senior Safety Officer", joinDate:"2015-06-01", supervisorName:"HSE Superintendent", workLocation:"Sambarata Mine", jobLevel:"S3", performance:[89,87,91], potential:85, readiness:80, technical:["Risk assessment","Incident investigation","SMKP","Emergency response"], behavioral:["Courageous leadership","Communication","Discipline"], certifications:["AK3 Umum","POP","Lead Auditor SMKP"], projects:["Critical risk control verification","Zero harm campaign"], careerHistory:["Safety Inspector","Safety Officer","Senior Safety Officer"], aspiration:"HSE Superintendent", hse:{mcu:"Fit",simper:"Aktif",incidentFreeMonths:72}, assessment:{iq:115,eq:89,leadership:87} },
  { name:"Dewi Anggraini", email:"dewi.anggraini@berau.co.id", nik:"BC10078", department:"Geology", position:"Senior Mine Geologist", joinDate:"2014-09-22", supervisorName:"Technical Services Manager", workLocation:"Lati Mine", jobLevel:"S3", performance:[92,88,89], potential:89, readiness:83, technical:["Geological modeling","Coal quality","Resource estimation","Mine reconciliation"], behavioral:["Scientific thinking","Collaboration","Planning"], certifications:["CPI Resources","POP"], projects:["Geological model accuracy uplift","Coal quality recovery study"], careerHistory:["Junior Geologist","Mine Geologist","Senior Mine Geologist"], aspiration:"Geology Superintendent", hse:{mcu:"Fit",simper:"Aktif",incidentFreeMonths:61}, assessment:{iq:130,eq:80,leadership:84} },
  { name:"Fajar Ramadhan", email:"fajar.ramadhan@berau.co.id", nik:"BC10084", department:"Supply Chain", position:"Procurement Lead", joinDate:"2018-03-12", supervisorName:"Supply Chain Manager", workLocation:"Head Office", jobLevel:"M1", performance:[85,88,82], potential:86, readiness:78, technical:["Strategic sourcing","Contract management","Vendor performance","SAP MM"], behavioral:["Negotiation","Commercial acumen","Influencing"], certifications:["CPSM","SAP MM"], projects:["Tyre contract saving 8%","Vendor consolidation"], careerHistory:["Buyer","Senior Buyer","Procurement Lead"], aspiration:"Supply Chain Manager", hse:{mcu:"Fit",simper:"Tidak diperlukan",incidentFreeMonths:74}, assessment:{iq:119,eq:85,leadership:82} },
  { name:"Maya Lestari", email:"maya.lestari@berau.co.id", nik:"BC10091", department:"Information Technology", position:"Data & Integration Lead", joinDate:"2019-07-01", supervisorName:"IT Manager", workLocation:"Head Office", jobLevel:"M1", performance:[93,90,88], potential:94, readiness:87, technical:["Data architecture","SAP integration","Cloud platform","Cyber security"], behavioral:["Innovation","Agile leadership","Stakeholder management"], certifications:["Azure Data Engineer","TOGAF","ITIL"], projects:["Mine data platform","SAP integration modernization"], careerHistory:["Business Analyst","Data Engineer","Data & Integration Lead"], aspiration:"IT Manager", hse:{mcu:"Fit",simper:"Tidak diperlukan",incidentFreeMonths:79}, assessment:{iq:132,eq:88,leadership:90} },
  { name:"Yusuf Maulana", email:"yusuf.maulana@berau.co.id", nik:"BC10104", department:"Mine Planning", position:"Senior Mine Planning Engineer", joinDate:"2016-11-14", supervisorName:"Technical Services Superintendent", workLocation:"Binungan Mine", jobLevel:"S3", performance:[90,92,86], potential:91, readiness:85, technical:["Long-term mine planning","Deswik","Reserve optimization","Economic evaluation"], behavioral:["Systems thinking","Communication","Decision making"], certifications:["POM","Deswik Advanced"], projects:["Five-year mine plan optimization","Haul distance reduction"], careerHistory:["Mine Engineer","Mine Planning Engineer","Senior Mine Planning Engineer"], aspiration:"Mine Planning Superintendent", hse:{mcu:"Fit",simper:"Aktif",incidentFreeMonths:58}, assessment:{iq:127,eq:83,leadership:88} },
  { name:"Intan Permata", email:"intan.permata@berau.co.id", nik:"BC10117", department:"Community Development", position:"Community Development Specialist", joinDate:"2018-05-21", supervisorName:"External Relations Manager", workLocation:"Tanjung Redeb", jobLevel:"S2", performance:[88,86,90], potential:87, readiness:79, technical:["Social mapping","Community program design","Impact measurement","Stakeholder engagement"], behavioral:["Empathy","Conflict resolution","Communication"], certifications:["Social Return on Investment","CSR Practitioner"], projects:["Local enterprise acceleration","Post-mining livelihood program"], careerHistory:["Community Officer","Community Development Specialist"], aspiration:"Community Development Superintendent", hse:{mcu:"Fit",simper:"Tidak diperlukan",incidentFreeMonths:76}, assessment:{iq:118,eq:94,leadership:84} },
  { name:"Andika Wijaya", email:"andika.wijaya@berau.co.id", nik:"BC10125", department:"Coal Processing Plant", position:"CPP Shift Supervisor", joinDate:"2011-10-10", supervisorName:"CPP Superintendent", workLocation:"Lati CPP", jobLevel:"S3", performance:[84,85,88], potential:80, readiness:81, technical:["Coal handling","Plant operations","Quality control","Shift management"], behavioral:["Operational discipline","Team leadership","Problem solving"], certifications:["POP","K3 Listrik"], projects:["Crusher throughput stabilization","ROM contamination reduction"], careerHistory:["Plant Operator","Control Room Operator","CPP Shift Supervisor"], aspiration:"CPP Superintendent", hse:{mcu:"Fit",simper:"Aktif",incidentFreeMonths:88}, assessment:{iq:112,eq:84,leadership:85} },
  { name:"Clara Wulandari", email:"clara.wulandari@berau.co.id", nik:"BC10139", department:"Legal & Compliance", position:"Senior Legal Counsel", joinDate:"2017-04-17", supervisorName:"Legal Manager", workLocation:"Head Office", jobLevel:"S3", performance:[91,93,89], potential:90, readiness:86, technical:["Mining law","Contract law","Compliance","Corporate governance"], behavioral:["Judgement","Influencing","Integrity"], certifications:["PERADI","Compliance Professional"], projects:["Mining permit assurance","Contract governance framework"], careerHistory:["Legal Officer","Legal Counsel","Senior Legal Counsel"], aspiration:"Legal & Compliance Manager", hse:{mcu:"Fit",simper:"Tidak diperlukan",incidentFreeMonths:92}, assessment:{iq:129,eq:87,leadership:88} },
  { name:"Rizky Kurniawan", email:"rizky.kurniawan@berau.co.id", nik:"BC10146", department:"Environment", position:"Environmental Engineer", joinDate:"2020-01-13", supervisorName:"Environment Superintendent", workLocation:"Sambarata Mine", jobLevel:"S2", performance:[87,84,86], potential:90, readiness:76, technical:["Mine rehabilitation","Water management","Environmental monitoring","AMDAL"], behavioral:["Learning agility","Collaboration","Planning"], certifications:["AMDAL A","POP"], projects:["Progressive rehabilitation analytics","Settling pond improvement"], careerHistory:["Graduate Environmental Engineer","Environmental Engineer"], aspiration:"Environment Superintendent", hse:{mcu:"Fit",simper:"Aktif",incidentFreeMonths:49}, assessment:{iq:123,eq:85,leadership:80} },
  { name:"Putri Maharani", email:"putri.maharani@berau.co.id", nik:"BC10158", department:"Learning & Development", position:"Learning Design Specialist", joinDate:"2019-02-04", supervisorName:"People Development Manager", workLocation:"Head Office", jobLevel:"S2", performance:[89,92,87], potential:93, readiness:82, technical:["Competency framework","Learning design","Assessment","LMS analytics"], behavioral:["Facilitation","Creativity","Coaching"], certifications:["CPLP","Assessment Center Assessor"], projects:["Supervisor academy","Technical competency dictionary"], careerHistory:["Training Officer","Learning Design Specialist"], aspiration:"People Development Manager", hse:{mcu:"Fit",simper:"Tidak diperlukan",incidentFreeMonths:81}, assessment:{iq:125,eq:92,leadership:86} },
  { name:"Hendra Gunawan", email:"hendra.gunawan@berau.co.id", nik:"BC10166", department:"Hauling & Logistics", position:"Hauling Supervisor", joinDate:"2013-12-02", supervisorName:"Logistics Superintendent", workLocation:"Binungan Mine", jobLevel:"S3", performance:[83,86,85], potential:81, readiness:80, technical:["Hauling operations","Dispatch","Road maintenance","Fatigue management"], behavioral:["Safety leadership","Execution","Team management"], certifications:["POP","POM","Defensive Driving"], projects:["Haul cycle improvement","Fatigue risk reduction"], careerHistory:["Dispatcher","Hauling Foreman","Hauling Supervisor"], aspiration:"Logistics Superintendent", hse:{mcu:"Fit",simper:"Aktif",incidentFreeMonths:69}, assessment:{iq:113,eq:83,leadership:84} },
  { name:"Anisa Fitri", email:"anisa.fitri@berau.co.id", nik:"BC10172", department:"Internal Audit", position:"Senior Internal Auditor", joinDate:"2018-09-03", supervisorName:"Head of Internal Audit", workLocation:"Head Office", jobLevel:"S3", performance:[92,90,93], potential:89, readiness:85, technical:["Risk-based audit","Data analytics","Internal control","Fraud assessment"], behavioral:["Integrity","Critical thinking","Communication"], certifications:["CIA","CISA"], projects:["Continuous controls monitoring","Procurement audit analytics"], careerHistory:["Internal Auditor","Senior Internal Auditor"], aspiration:"Internal Audit Manager", hse:{mcu:"Fit",simper:"Tidak diperlukan",incidentFreeMonths:83}, assessment:{iq:131,eq:86,leadership:87} },
  { name:"Galang Prakoso", email:"galang.prakoso@berau.co.id", nik:"BC10185", department:"Mine Survey", position:"Senior Surveyor", joinDate:"2015-03-16", supervisorName:"Mine Planning Superintendent", workLocation:"Lati Mine", jobLevel:"S3", performance:[86,88,87], potential:84, readiness:79, technical:["Mine surveying","Drone mapping","Volume reconciliation","GIS"], behavioral:["Accuracy","Collaboration","Continuous improvement"], certifications:["Juru Ukur Tambang","Drone Pilot","POP"], projects:["Drone survey automation","Stockpile reconciliation"], careerHistory:["Surveyor","Senior Surveyor"], aspiration:"Survey Superintendent", hse:{mcu:"Fit",simper:"Aktif",incidentFreeMonths:64}, assessment:{iq:120,eq:81,leadership:82} },
  { name:"Vina Oktaviani", email:"vina.oktaviani@berau.co.id", nik:"BC10193", department:"Corporate Affairs", position:"Corporate Communication Lead", joinDate:"2017-10-23", supervisorName:"Corporate Affairs Manager", workLocation:"Head Office", jobLevel:"M1", performance:[88,91,89], potential:91, readiness:83, technical:["Corporate communication","Crisis communication","Media relations","ESG reporting"], behavioral:["Influencing","Composure","Storytelling"], certifications:["Strategic Communication","GRI Reporting"], projects:["ESG narrative program","Crisis communication playbook"], careerHistory:["Communication Officer","Senior Communication Specialist","Corporate Communication Lead"], aspiration:"Corporate Affairs Manager", hse:{mcu:"Fit",simper:"Tidak diperlukan",incidentFreeMonths:86}, assessment:{iq:122,eq:91,leadership:87} }
];
